FROM ghcr.io/graalvm/native-image-community:17@sha256:9dbd4eb0934b5b9ec4c361d1f910eb6267090339b483b72e7e85c79b3ac1e8bb
USER root
RUN microdnf update -y && \
    microdnf install -y git gcc gcc-c++ curl ca-certificates binutils make tar gzip && \
    microdnf clean all
COPY install-musl.sh /opt/install-musl.sh
RUN chmod +x /opt/install-musl.sh && cd /opt && ./install-musl.sh
ENV MUSL_HOME=/opt/musl-toolchain
ENV PATH="/opt/musl-toolchain/bin:${PATH}"
RUN git config --global --add safe.directory '*'
