FROM ghcr.io/graalvm/native-image-community:23@sha256:5a28da013d97ac66033b6c836015c7ee7f5d3e07c705d51f1e6c26a04fd17b8e AS graalvm
FROM ubuntu:22.04@sha256:0e0a0fc6d18feda9db1590da249ac93e8d5abfea8f4c3c0c849ce512b5ef8982
ENV JAVA_HOME=/usr/lib64/graalvm/graalvm-community-java23
ENV PATH="${JAVA_HOME}/bin:${PATH}"
COPY --from=graalvm ${JAVA_HOME} ${JAVA_HOME}
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      git build-essential curl ca-certificates binutils make tar gzip && \
    rm -rf /var/lib/apt/lists/*
COPY install-musl.sh /opt/install-musl.sh
RUN chmod +x /opt/install-musl.sh && cd /opt && ./install-musl.sh
ENV MUSL_HOME=/opt/musl-toolchain
ENV PATH="/opt/musl-toolchain/bin:${PATH}"
RUN git config --global --add safe.directory '*'
