package io.temporal.internal.nexus;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import java.io.IOException;
import java.util.Base64;
import org.junit.Assert;
import org.junit.Test;

public class WorkflowRunTokenTest {
  private static final ObjectWriter ow =
      new ObjectMapper().registerModule(new Jdk8Module()).writer();
  private static final ObjectReader or =
      new ObjectMapper().registerModule(new Jdk8Module()).reader();
  private static final Base64.Encoder encoder = Base64.getUrlEncoder().withoutPadding();

  @Test
  public void serializeWorkflowRunToken() throws JsonProcessingException {
    OperationToken token =
        new OperationToken(OperationTokenType.WORKFLOW_RUN, "namespace", "workflowId");
    String json = ow.writeValueAsString(token);
    final JsonNode node = new ObjectMapper().readTree(json);
    System.out.println(json);
    // Assert that the serialized JSON is as expected
    Assert.assertEquals(1, node.get("t").asInt());
    Assert.assertEquals("namespace", node.get("ns").asText());
    Assert.assertEquals("workflowId", node.get("wid").asText());
    // Version field should not be serialized as it is null
    Assert.assertFalse(node.has("v"));
  }

  @Test
  public void deserializeWorkflowRunTokenWithVersion() throws IOException {
    String json = "{\"t\":1,\"ns\":\"namespace\",\"wid\":\"workflowId\",\"v\":1}";
    JavaType reference = new ObjectMapper().getTypeFactory().constructType(OperationToken.class);
    OperationToken token = new ObjectMapper().readValue(json.getBytes(), reference);
    // Assert that the serialized JSON is as expected
    Assert.assertEquals(OperationTokenType.WORKFLOW_RUN, token.getType());
    Assert.assertEquals(new Integer(1), token.getVersion());
    Assert.assertEquals("namespace", token.getNamespace());
    Assert.assertEquals("workflowId", token.getWorkflowId());
  }

  @Test
  public void deserializeWorkflowRunToken() throws IOException {
    String json = "{\"t\":1,\"ns\":\"namespace\",\"wid\":\"workflowId\"}";
    JavaType reference = new ObjectMapper().getTypeFactory().constructType(OperationToken.class);
    OperationToken token = new ObjectMapper().readValue(json.getBytes(), reference);
    // Assert that the serialized JSON is as expected
    Assert.assertEquals(OperationTokenType.WORKFLOW_RUN, token.getType());
    Assert.assertNull(null, token.getVersion());
    Assert.assertEquals("namespace", token.getNamespace());
    Assert.assertEquals("workflowId", token.getWorkflowId());
  }

  @Test
  public void failLoadOldWorkflowRunToken() {
    String operationToken = "AAAAA-BBBBB-CCCCC";
    Assert.assertThrows(
        IllegalArgumentException.class,
        () -> OperationTokenUtil.loadWorkflowIdFromOperationToken(operationToken));
  }

  @Test
  public void loadWorkflowIdFromOperationToken() {
    String json = "{\"t\":1,\"ns\":\"namespace\",\"wid\":\"workflowId\"}";

    OperationToken token =
        OperationTokenUtil.loadOperationToken(encoder.encodeToString(json.getBytes()));
    Assert.assertEquals("workflowId", token.getWorkflowId());
    Assert.assertEquals("namespace", token.getNamespace());
    Assert.assertNull(token.getVersion());
    Assert.assertEquals(OperationTokenType.WORKFLOW_RUN, token.getType());

    Assert.assertEquals(
        "workflowId",
        OperationTokenUtil.loadWorkflowIdFromOperationToken(
            encoder.encodeToString(json.getBytes())));
  }

  @Test
  public void loadWorkflowIdFromGoOperationToken() {
    // This is a token generated by the Go SDK, use this to test compatibility
    // across SDKs.
    String goOperationToken = "eyJ2IjowLCJ0IjoxLCJucyI6Im5zIiwid2lkIjoidyJ9";

    OperationToken token = OperationTokenUtil.loadOperationToken(goOperationToken);
    Assert.assertEquals("w", token.getWorkflowId());
    Assert.assertEquals("ns", token.getNamespace());
    Assert.assertEquals(Integer.valueOf(0), token.getVersion());
    Assert.assertEquals(OperationTokenType.WORKFLOW_RUN, token.getType());
  }

  @Test
  public void roundTripActivityExecutionToken() throws JsonProcessingException {
    String encoded = OperationTokenUtil.generateActivityExecutionOperationToken("act-1", "ns");
    OperationToken token = OperationTokenUtil.loadOperationToken(encoded);
    Assert.assertEquals(OperationTokenType.ACTIVITY_EXECUTION, token.getType());
    Assert.assertEquals("act-1", token.getActivityId());
    Assert.assertEquals("ns", token.getNamespace());
    Assert.assertNull(token.getWorkflowId());
    Assert.assertNull(token.getRunId());
    Assert.assertNull(token.getVersion());

    // Also exercise the symmetric activityId loader.
    Assert.assertEquals("act-1", OperationTokenUtil.loadActivityIdFromOperationToken(encoded));
  }

  @Test
  public void roundTripActivityExecutionTokenWithRunId() throws JsonProcessingException {
    String encoded =
        OperationTokenUtil.generateActivityExecutionOperationToken("act-1", "run-1", "ns");
    OperationToken token = OperationTokenUtil.loadOperationToken(encoded);
    Assert.assertEquals(OperationTokenType.ACTIVITY_EXECUTION, token.getType());
    Assert.assertEquals("act-1", token.getActivityId());
    Assert.assertEquals("run-1", token.getRunId());
    Assert.assertEquals("ns", token.getNamespace());
    Assert.assertNull(token.getWorkflowId());
    Assert.assertNull(token.getVersion());
  }

  @Test
  public void activityExecutionTokenOmitsRunIdWhenNull() throws JsonProcessingException {
    // The header-token path passes runId=null and must produce a payload byte-identical to the
    // two-arg overload — the runId-aware overload is the *only* one used in code now.
    String withRunId =
        OperationTokenUtil.generateActivityExecutionOperationToken("act-1", null, "ns");
    String withoutRunId = OperationTokenUtil.generateActivityExecutionOperationToken("act-1", "ns");
    Assert.assertEquals(withoutRunId, withRunId);
  }

  @Test
  public void workflowRunTokenBytesByteIdenticalSnapshot() throws JsonProcessingException {
    String encoded = OperationTokenUtil.generateWorkflowRunOperationToken("wf-1", "ns");
    // The encoded token must remain byte-identical for cross-SDK compatibility.
    // Snapshot captured from the current (pre-aid) SDK output.
    Assert.assertEquals("eyJ0IjoxLCJucyI6Im5zIiwid2lkIjoid2YtMSJ9", encoded);
  }

  @Test
  public void malformedActivityTokenRejected() {
    String malformed = "{\"t\":4,\"ns\":\"ns\",\"aid\":\"\"}";
    IllegalArgumentException ex =
        Assert.assertThrows(
            IllegalArgumentException.class,
            () ->
                OperationTokenUtil.loadOperationToken(
                    encoder.encodeToString(malformed.getBytes())));
    Assert.assertTrue(
        "expected 'missing activity ID' in message but got: " + ex.getMessage(),
        ex.getMessage().contains("missing activity ID"));
  }

  @Test
  public void unknownOperationTokenTypeRejected() {
    String unknown = "{\"t\":7,\"ns\":\"ns\",\"wid\":\"x\"}";
    IllegalArgumentException ex =
        Assert.assertThrows(
            IllegalArgumentException.class,
            () ->
                OperationTokenUtil.loadOperationToken(encoder.encodeToString(unknown.getBytes())));
    Assert.assertTrue(
        "expected 'unknown operation token type' in message but got: " + ex.getMessage(),
        ex.getMessage().contains("unknown operation token type"));
  }

  @Test
  public void loadWorkflowRunRejectsActivityToken() throws JsonProcessingException {
    String activityToken =
        OperationTokenUtil.generateActivityExecutionOperationToken("act-1", "ns");
    IllegalArgumentException ex =
        Assert.assertThrows(
            IllegalArgumentException.class,
            () -> OperationTokenUtil.loadWorkflowRunOperationToken(activityToken));
    Assert.assertTrue(
        "expected 'incorrect operation token type' in message but got: " + ex.getMessage(),
        ex.getMessage().contains("incorrect operation token type"));
  }

  @Test
  public void loadWorkflowIdFromBadOperationToken() {
    // Bad token, empty json
    String badTokenEmptyJson = "{}";
    Assert.assertThrows(
        IllegalArgumentException.class,
        () ->
            OperationTokenUtil.loadOperationToken(
                encoder.encodeToString(badTokenEmptyJson.getBytes())));

    // Bad token, missing the "wid" field
    String badTokenMissingWorkflow = "{\"t\":1,\"ns\":\"namespace\"}";
    Assert.assertThrows(
        IllegalArgumentException.class,
        () ->
            OperationTokenUtil.loadOperationToken(
                encoder.encodeToString(badTokenMissingWorkflow.getBytes())));

    // Bad token, unknown version
    String badTokenUnknownVersion =
        "{\"t\":1,\"ns\":\"namespace\", \"wid\":\"workflowId\", \"v\":1}";
    Assert.assertThrows(
        IllegalArgumentException.class,
        () ->
            OperationTokenUtil.loadOperationToken(
                encoder.encodeToString(badTokenUnknownVersion.getBytes())));

    // Bad token, unknown type (also has bad version, so loadOperationToken rejects on version)
    String badTokenUnknownType = "{\"t\":4,\"ns\":\"namespace\", \"wid\":\"workflowId\", \"v\":1}";
    Assert.assertThrows(
        IllegalArgumentException.class,
        () ->
            OperationTokenUtil.loadOperationToken(
                encoder.encodeToString(badTokenUnknownType.getBytes())));

    // Bad token, unknown type with valid version — loadWorkflowRunOperationToken rejects on type
    String badTokenWrongType = "{\"t\":4,\"ns\":\"namespace\", \"wid\":\"workflowId\"}";
    Assert.assertThrows(
        IllegalArgumentException.class,
        () ->
            OperationTokenUtil.loadWorkflowRunOperationToken(
                encoder.encodeToString(badTokenWrongType.getBytes())));
  }
}
