package io.temporal.serviceclient;

public enum GrpcFailure {
  CANCELLATION_ALREADY_REQUESTED,
  CLIENT_VERSION_NOT_SUPPORTED,
  CURRENT_BRANCH_CHANGED,
  DOMAIN_ALREADY_EXISTS_FAILURE,
  DOMAIN_NOT_ACTIVE,
  EVENT_ALREADY_STARTED,
  QUERY_FAILED,
  RETRY_TASK,
  RETRY_TASK_V2,
  SHARD_OWNERSHIP_LOST,
  WORKFLOW_EXECUTION_ALREADY_STARTED_FAILURE
}
