system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
system.enableActivityEagerExecution:
  - value: true
system.enableEagerWorkflowStart:
  - value: true
frontend.enableUpdateWorkflowExecution:
  - value: true
frontend.enableUpdateWorkflowExecutionAsyncAccepted:
  - value: true
frontend.workerVersioningWorkflowAPIs:
  - value: true
frontend.workerVersioningDataAPIs:
  - value: true
history.MaxBufferedQueryCount:
  - value: 100000 