system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
system.enableActivityEagerExecution:
  - value: true
    constraints: {}
system.enableEagerWorkflowStart:
  - value: true
    constraints: {}
