system.forceSearchAttributesCacheRefreshOnRead:
  - value: true
system.enableActivityEagerExecution:
  - value: true
    constraints: {}
system.enableEagerWorkflowStart:
  - value: true
    constraints: {}
frontend.enableUpdateWorkflowExecution:
  - value: true
    constraints: {}
frontend.enableUpdateWorkflowExecutionAsyncAccepted:
  - value: true
    constraints: { }