FROM ghcr.io/graalvm/native-image-community:23@sha256:5a28da013d97ac66033b6c836015c7ee7f5d3e07c705d51f1e6c26a04fd17b8e AS graalvm
FROM ubuntu:18.04@sha256:152dc042452c496007f07ca9127571cb9c29697f42acbfad72324b2bb2e43c98
ENV JAVA_HOME=/usr/lib64/graalvm/graalvm-community-java23
ENV PATH="${JAVA_HOME}/bin:${PATH}"
COPY --from=graalvm ${JAVA_HOME} ${JAVA_HOME}
RUN apt-get update --allow-releaseinfo-change && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      software-properties-common && \
    add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      git build-essential zlib1g-dev gcc-10 g++-10 && \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 \
      --slave /usr/bin/g++ g++ /usr/bin/g++-10 && \
    rm -rf /var/lib/apt/lists/*
RUN git config --global --add safe.directory '*'
