package io.temporal.nexus;

import io.temporal.common.Experimental;
import java.util.Objects;
import javax.annotation.Nullable;

/**
 * Input to {@link TemporalOperationHandler#cancelActivityExecution} describing the activity
 * execution to cancel.
 */
@Experimental
public final class CancelActivityExecutionInput {

  private final String activityId;
  private final @Nullable String runId;

  public CancelActivityExecutionInput(String activityId, @Nullable String runId) {
    this.activityId = Objects.requireNonNull(activityId);
    this.runId = runId;
  }

  /** Returns the activity ID extracted from the operation token. */
  public String getActivityId() {
    return activityId;
  }

  /**
   * Returns the activity run ID extracted from the operation token, or {@code null} if absent.
   *
   * <p>Run ID is only present on operation tokens that were generated by this SDK AFTER the start
   * activity RPC completed. Tokens originating from the activity completion callback header do not
   * carry a run ID.
   */
  @Nullable
  public String getRunId() {
    return runId;
  }
}
