name: Code Coverage
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  code-coverage:
    runs-on: ubuntu-latest-16-cores
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          java-version: "23"
          distribution: "temurin"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@ac396bf1a80af16236baf54bd7330ae21dc6ece5 # v6

      - name: Run Tests
        run: ./gradlew test -x spotlessCheck -x spotlessApply -Pjacoco -PtestJavaVersion=23
        continue-on-error: true

      - name: Run Test Coverage
        run: ./gradlew testCodeCoverageReport -Pjacoco

      - name: Publish Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: ./gradlew coverallsJacoco -Pjacoco
