FROM openjdk:8-alpine

# Install dependencies using apk
RUN apk update && apk add --virtual build-dependencies build-base gcc

# Compile source
# Note that environment variables are not supported in --from, so hardcoding the Thrift version
COPY --from=thrift:0.9.3 /usr/local/bin/thrift /usr/local/bin/thrift

# Cleanup packages and remove cache
RUN apk del build-dependencies wget && rm -rf /var/cache/apk/*

RUN mkdir /temporal-java-client
WORKDIR /temporal-java-client